### ISSUE TITLE
Неверная версия в манифесте

### ISSUE THREAD

**Issue by nixel2007** [artbear/1testrunner#2]

**Comment by artbear** [comment]
Что не так? в ветке девелоп все совпадает, версия 1.2

**Comment by nixel2007** [comment]
https://github.com/artbear/1testrunner/blob/master/packagedef

**Comment by artbear** [comment]
Версию 1.3 выпустить?

**Comment by nixel2007** [comment]
до 1.2 хотя бы повысить. в мастере 1.1, хотя код уже от 1.2

**Comment by artbear** [comment]
Перевыпустил релиз 1.2
