### ISSUE TITLE
Ошибка в работе с делегатами, ПередЗапускомТеста() вызывается с параметром Неопределено

### ISSUE THREAD

**Issue by leemuar** [artbear/1testrunner#20]
Текущая версия мастер-ветки (https://github.com/artbear/1testrunner/commit/154e5a57311967273cbc7ebb8a5dd5fcc0ac3d6d) не проходит собственные же тесты:

https://imgur.com/UwAdxGo

Судя по всему ПередЗапускомТеста() вызывается делегатом с одним параметром, равным Неопределено,  что приводит к ошибке "Неверное количество параметров"

**Comment by nixel2007** [comment]
@artbear а ты рисковый - переводить тестраннер на делегаты

**Comment by artbear** [comment]
Дело в том, что 1тестраннер зависит от библиотеки delegate версии 0.1.2
А по какой-то причине релиз этой библиотеки выпущен, а вот в хабе библиотек ее нет :worried:
в итоге 1тестраннер юзает старую версию 0.1.1 делегата, в котором была ошибка, на которую ты и нарываешься 

Видимо, когда opm push не работал, и публиковали пакеты через пуш тебя, что-то не до конца сделали :(

сейчас исправил.

**Comment by artbear** [comment]
@nixel2007 никакого риска, все работает и тесты проходят :)
