### ISSUE TITLE
Лишний вызов логирования ошибки

### ISSUE THREAD

**Issue by leemuar** [artbear/1testrunner#23]
https://github.com/artbear/1testrunner/blob/b7bec176d34167646a991b351c4e98b4de0534a2/tests/exec-tests.os#L88

Мне кажется этот безусловный вызов логирования ошибки лишний. При запуске самотестирования в логи постоянно пишется ошибка, это напрягает.

https://files.gitter.im/EvilBeaver/oscript-library/7IAV/image.png

Есть в этом какой-то сакральный смысл или можно удалить эту строку?

**Comment by artbear** [comment]
Да, там нужно поставить Лог.Отладка, конечно
