### ISSUE TITLE
Не работает на вышедшей версии 1.0.20

### ISSUE THREAD

**Issue by khorevaa** [artbear/1testrunner#30]
@artbear  Надо выпустить версию из девелоа

**Comment by artbear** [comment]
Я запустил на ночнике только что, работает.
@khorevaa Дай описание ошибки, пожалуйста.

**Comment by khorevaa** [comment]
@artbear 
Вот PR который правил develop https://github.com/artbear/1testrunner/pull/29

**Comment by khorevaa** [comment]
@artbear 
```
ОШИБКА: Упал метод ПередЗапускомТеста
Тест: <ТестДолжен_ПроверитьСозданиеИнтерфейсаИзОбъекта>
Файл: </work_dir/tests/ИнтерфейсОбъекта_test.os> 
Сообщение: {Модуль /usr/share/oscript/lib/delegate/src/Делегат.os / Ошибка в строке: 61 / Метод объекта не обнаружен ({/work_dir/tests/ИнтерфейсОбъекта_test.os}::ПередЗапускомТеста)}
```

**Comment by artbear** [comment]
@khorevaa Все равно непонятно :)
Из сообщения ошибки я вижу, что в твоем файле нет метода `ПередЗапускомТеста`

**Comment by khorevaa** [comment]
Метод то не обязательный...

**Comment by artbear** [comment]
Упс, твоя правда :)

**Comment by khorevaa** [comment]
@artbear  Для починки надо всего лишь выпустить новый релиз из ветки девелоп!

**Comment by artbear** [comment]
Выпустил новый релиз 1 .5.3
Метро рулит

**Comment by khorevaa** [comment]
@artbear  А на хаб закинул? (opm push?)
