### ISSUE TITLE
Тестирование logos

### ISSUE THREAD

**Issue by EvilBeaver** [artbear/1testrunner#31]
При тестировании logos на коммите 7905359efd347b7308b18caa37e7adbae0f61799 командой

    1testrunner ./tests/logos-test.os

Ошибок не выдается, однако, если тестировать через таски opm

    opm test

То падает один тест: 

```
Тест №27: Тест_ДолженВывестиВЛогПростуюСтрокуСПустымПараметром

ОШИБКА: Тест: <Тест_ДолженВывестиВЛогПростуюСтрокуСПустымПараметром>
Файл: <D:\Users\ovsia\Documents\GITS\library-repos\logos\tests\logos-test.os>
Сообщение: {Модуль C:\Program Files (x86)\OneScript\lib\opm\oscript_modules\asserts\src\xunit-asserts.os / Ошибка в строке: 30 / Сравниваемые значения (ИНФОРМАЦИЯ - Привет <%1>; ИНФОРМАЦИЯ - Привет <>) не равны, а хотели, чтобы были равны.}
                ВызватьИсключение(СообщениеОшибки);
```

**Comment by nixel2007** [comment]
Опм подгружает логос из своих оскрипт_модулес. Надо запускать через oscript tasks/test.os

**Comment by nixel2007** [comment]
@EvilBeaver я думаю, эту проблему можно решить на уровне опм. Сейчас он выполняет таски через загрузить сценарий. А можно переделать на запуск оскрипт из консоли и пути к таске

**Comment by artbear** [comment]
@EvilBeaver @nixel2007 Как я уже много раз писал, способ запуска `запуск оскрипт из консоли и пути к таске` будет работать, 
ТОЛЬКО если первым `#Использовать` внутри `test.os` будет путь к локальному пути, 
например, `#Использовать ".."` или `#Использовать "..\src"`

Если вначале будет стоять не локальный путь, а какая-то другая библиотека, например, `#Использовать logos`, то почти наверняка будут юзаться установленные библиотеки, а не локальные, что приведет к багу из ишуза.

**Comment by artbear** [comment]
@EvilBeaver @nixel2007 Ну и соответственно, простого решения через opm не будет, т.к. тесты должны быть завязаны на конкретную структуру каталогов тестируемого пакета :(

**Comment by nixel2007** [comment]
@artbear причём здесь тесты? Таски вообще ничего не знают про тесты. Таски просто запускаются и все. А ТекущийКаталог и отнлсительные пути никто не отменял

**Comment by artbear** [comment]
@nixel2007 Да, я неверно понял и согласен с тобой.
Нужно переходить именно на запуск `oscript путь/таск параметры...`
