### ISSUE TITLE
#Использовать 1testrunner

### ISSUE THREAD

**Issue by nixel2007** [artbear/1testrunner#6]
Сабж. Как?
Сейчас тестраннер жрет аргументы командной строки даже в файле, в котором есть только она директива Использовать и пытается сразу запуститься

**Comment by artbear** [comment]
@nixel2007 Не совсем понял про "жрет аргументы ком.строки".
Поясни

**Comment by nixel2007** [comment]
скрипт из одной строки
```bsl
#Использовать 1testrunner
```

вызывает выполнение https://github.com/artbear/1testrunner/blob/master/testrunner.os#L808

Я хочу интерфейс, аналогичный 1bdd - отдельный класс, экземпляр которого я бы мог создать в своем скрипте и выполнить параметры.
